name: nepanikar
description: First aid for psychological issues.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  go_router: ^4.5.0
  intl: ^0.17.0
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.11
  provider: ^6.0.3

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.0.14
  lint: ^1.10.0

flutter:
  uses-material-design: true
  generate: true
