name: Continuous Integration / build
on:
  push:
    branches: [ main ]
  pull_request:

env:
  flutter_version: '3.3.9'
  CI: false
  #  These are debug values and are not used in production (workaround for this error https://stackoverflow.com/q/54457245):
  CM_KEYSTORE_PATH: 'nepanikar_debug.keystore'
  CM_KEYSTORE_PASSWORD: 'android'
  CM_KEY_ALIAS: 'androiddebugkey'
  CM_KEY_PASSWORD: 'android'


jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Flutter SDK cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          cache: true
          cache-key: ${{ runner.OS }}-flutter-${{ env.flutter_version }}
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Build apk
        run: flutter build apk --debug